### ISSUE TITLE
Add support for multiple "root folders"

### ISSUE THREAD

**Issue by c10l** [motepair/motepair#15]
Currently motepair only syncs the main root folder of an Atom window. Here's the behaviour I observed:
#### Same primary root:
- On one window, open `ProjectA`, then add `ProjectB` (right-click on file tree, select _Add Root Folder_).
- Repeat the process for the second window.
- Connect both to the same `motepair` session.

**Expected Result:**
Files from both projects open, close and mirror on both windows.

**Actual Result:**
Only files from `ProjectA` are correctly synced. When a file from `ProjectB` is opened on one window, nothing happens on the other side. Events from both are still getting sent over, resulting in gibberish on both sides.
#### Different primary root:
- On one window, open `ProjectA`, then add `ProjectB` (right-click on file tree, select _Add Root Folder_).
- On the other window, open `ProjectB`, then add `ProjectA`
- Connect both to the same `motepair` session.

**Expected Result:**
Files from both projects open, close and mirror on both windows.

**Actual Result:**
Unpredictable. No file/tab events get reflected on the opposite side (open file, close tab, etc). Some cursor events do.

**Comment by brunowego** [comment]
+1 :+1:

**Comment by brunowego** [comment]
I not know if is a bug or I not understood the right way, but only sync the root directory between a Windows and OSX machines.

**Comment by awilkins** [comment]
Having a look at this. It's basically essential if you're working with more than one Git tree because you have to add each of them as a project folder for Atom to love them properly.

Should be doable by...
- Replacing `project.relativize` calls with `project.relativizePath`
  - Or add a filePath property to `data`, if you want to keep compatibility with older clients
  - This return an 2-element array of project folder / subpath
- Adding a function that works out which open project folder matches filePath[0] best for that file
  - Could be as simple as just matching the last folder name
  - It might be harder in the the case where you have multiple folders with the same name open (which I have right now - the motepair source plus I'm editing my installed package...) - but name match should cover the vast majority of cases and is better than the current caveat of only editing one project.
- Munging data.filePath through that function for all uses

**Comment by luizbafilho** [comment]
Hi @awilkins feel free to create a pull request with that changes I would be glad to merge it.

**Comment by luizbafilho** [comment]
@awilkins Version 0.22.0 published. Thank you for the PR.
