### ISSUE TITLE
Option to disable tab switching

### ISSUE THREAD

**Issue by atroche** [motepair/motepair#30]
Hi! Motepair to work really well, but we're finding it almost unusable, because we can't separately browse the codebase. If one person switches tabs or opens up a new file, it interrupts the other person, who might be typing. Is there an easy way to disable this feature?

**Comment by luizbafilho** [comment]
@atroche it might be easy I'm gonna take a look at that.

**Comment by gangseok514** [comment]
I add opinion, While pair programming, User shouldn't decide whether file is saved or not.
Because Server has always latest document, so saving or not in client is meanless.
I think, hack the atom's internal function(promptToSaveItem in pane.coffee), make it always calls saveItem and returns true. (When user close the tab, it will save the file and close without confirm popup)

**Comment by luizbafilho** [comment]
Done in #32 thanks to @gangseok514 :+1:
